name: meal_mastermind
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  http: ^1.1.0
  image_picker: ^1.0.8
  flutter_spinkit: ^5.2.1
  geolocator: ^7.0.3
  url_launcher: ^6.0.6
  google_maps_flutter: ^2.2.5
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.6
  flutter_polyline_points: ^2.0.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  web: 0.1.4-beta

flutter:
  uses-material-design: true
